---
name: berghmans-checks
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install pipenv
      - run: pipenv sync
      - uses: pre-commit/action@v3.0.0
