name: build-test-publish

on:
  workflow_run:
    workflows: [berghmans-checks]
    types: [completed]
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/release-container
  PYTHON_VERSION: "3.12.3"
  NODE_VERSION: "20.x"
  TEST_TAG: "release-container:test"

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ env.TEST_TAG }}
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
      - run: docker run --rm ${{ env.TEST_TAG }} "python --version"
      - run: docker run --rm ${{ env.TEST_TAG }} "node --version"
      - run: docker run --rm ${{ env.TEST_TAG }} "semantic-release --version"
      - run: docker run --rm ${{ env.TEST_TAG }} "invoke --version"
      - run: docker run --rm ${{ env.TEST_TAG }} "cfn-lint --version"
      - run: docker run --rm ${{ env.TEST_TAG }} "pylint --version"
      - name: boto3 version
        run: docker run --rm ${{ env.TEST_TAG }} "python -c 'import boto3; print(boto3.__version__)'"
      - uses: actions/checkout@v4
      # - name: Run application-specific GitHub Action test, e.g. a semantic-release dry-run
      - name: Gather output
        id: set-output
        run: |
          PYTHON_VERSION=$(docker run --rm ${{ env.TEST_TAG }} python --version 2>&1 | awk '{print $2}')
          echo "python_version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
          NODE_VERSION=$(docker run --rm ${{ env.TEST_TAG }} node --version 2>&1 | awk -F 'v' '{print $2}')
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
    outputs:
      python_version: ${{ steps.set-output.outputs.python_version }}
      node_version: ${{ steps.set-output.outputs.node_version }}

  push:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Update environment variables
        id: vars
        run: |
          echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - id: extract-versions
        run: |
          PYTHON_MAJOR_MINOR=$(echo ${{ needs.test-action.outputs.python_version }} | awk -F. '{print $1"."$2}')
          NODE_MAJOR_MINOR=$(echo ${{ needs.test-action.outputs.node_version }} | awk -F. '{print $1"."$2}')
          echo "python_version=${{ needs.test-action.outputs.python_version }}" >> $GITHUB_OUTPUT
          echo "python_major_minor=$PYTHON_MAJOR_MINOR" >> $GITHUB_OUTPUT
          echo "node_version=${{ needs.test-action.outputs.node_version }}" >> $GITHUB_OUTPUT
          echo "node_major_minor=$NODE_MAJOR_MINOR" >> $GITHUB_OUTPUT
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,prefix=py${{ env.PYTHON_VERSION }}-node${{ env.NODE_VERSION }}-,suffix=,format=short
            type=raw,value=py${{ steps.extract-versions.outputs.python_version }}-node${{ steps.extract-versions.outputs.node_version }}
            type=raw,value=py${{ steps.extract-versions.outputs.python_major_minor }}-node${{ steps.extract-versions.outputs.node_major_minor }}
            type=raw,value=py${{ steps.extract-versions.outputs.python_version }}
            type=raw,value=py${{ steps.extract-versions.outputs.python_major_minor }}
          labels: |
            version.python=${{ steps.extract-versions.outputs.python_version }}
            version.nodejs=${{ steps.extract-versions.outputs.node_version }}
      - uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
      - name: Gather output
        id: set-output
        run: |
          echo "image_uri=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "$GITHUB_OUTPUT"
    outputs:
      image_uri: ${{ steps.set-output.outputs.image_uri }}

  test-action:
    needs: push
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.push.outputs.image_uri }}
    steps:
      - run: python --version
      - run: node --version
      - run: semantic-release --version
      - run: invoke --version
      - run: cfn-lint --version
      - run: pylint --version
      - name: boto3 version
        run: python -c "import boto3; print(boto3.__version__)"
      - uses: actions/checkout@v4
      # - name: Run application-specific GitHub Action test, e.g. a semantic-release dry-run
      - name: Gather output
        id: set-output
        run: |
          PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
          echo "python_version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
          NODE_VERSION=$(node --version 2>&1 | awk -F 'v' '{print $2}')
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
    outputs:
      python_version: ${{ steps.set-output.outputs.python_version }}
      node_version: ${{ steps.set-output.outputs.node_version }}
