name: test-versions

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to test"
        required: true
        type: string
      image:
        description: "The Docker image to use for the test"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - run: chown -R $(whoami) .
      - run: semantic-release --dry-run --branches ${{ github.ref_name }}
        env:
          GIT_AUTHOR_NAME: berghmans-bot
          GIT_AUTHOR_EMAIL: berghmans-bot@no-reply.com
          GIT_COMMITTER_NAME: berghmans-bot
          GIT_COMMITTER_EMAIL: berghmans-bot@no-reply.com
