name: test-sam-cli

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to test"
        required: true
        type: string
      image:
        description: "The Docker image to use for the test"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - run: invoke build
        working-directory: tests/sam-cli

  run-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install invoke
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: invoke build
        working-directory: tests/sam-cli

  run-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install invoke
        shell: bash
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: invoke build
        working-directory: tests/sam-cli
