name: test-versions

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to test"
        required: true
        type: string
      image:
        description: "The Docker image to use for the test"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
    steps:
      - run: python --version
      - run: node --version
      - run: semantic-release --version
      - run: invoke --version
      - run: cfn-lint --version
      - run: pylint --version
      - name: boto3 version
        run: python -c "import boto3; print(boto3.__version__)"
